{
 "title": "Kafka Producer",
 "tags": [ "kafka" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "k8s_cluster",
    "query": {
     "query": "label_values(kafka_producer_producer_metrics_request_rate, k8s_cluster)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(kafka_producer_producer_metrics_request_rate{k8s_cluster=\"$k8s_cluster\"}, job)"
    }
   },
   {
    "name": "topic",
    "query": {
     "query": "label_values(kafka_producer_producer_topic_metrics_record_send_rate{k8s_cluster=\"$k8s_cluster\", job=\"$job\"}, topic)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Topics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Messages produced per topic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sort_desc(sum(kafka_producer_producer_topic_metrics_record_send_rate{k8s_cluster=\"$k8s_cluster\", job=\"$job\", topic=~\"$topic\"}) by (topic) > 0)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Byte rate per topic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sort_desc(sum(kafka_producer_producer_topic_metrics_byte_rate{k8s_cluster=\"$k8s_cluster\", job=\"$job\", topic=~\"$topic\"}) by (topic) > 0)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  { "title": "General / Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Request Rate(Request to brokers/sec)",
   "type": "timeseries",
   "description": "Average number of requests received per second.\nThe request rate is the rate at which producers send data to brokers",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_producer_producer_metrics_request_rate{job=\"$job\", k8s_cluster=\"$k8s_cluster\"}",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Outgoing bytes per second",
   "type": "timeseries",
   "description": "producer network throughput.\nThe average number of outgoing bytes sent per second to all servers.\n",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "kafka_producer_producer_metrics_outgoing_byte_rate{job=\"$job\", k8s_cluster=\"$k8s_cluster\"}",
     "legendFormat": "{{client_id}}"
    },
    {
     "expr": "sum(kafka_producer_producer_metrics_outgoing_byte_rate{job=\"$job\", k8s_cluster=\"$k8s_cluster\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Request Latency Avg",
   "type": "timeseries",
   "description": "The average request latency in ms. The average request latency is a measure of the amount of time between when KafkaProducer.send() was called until the producer receives a response from the broker. (Acks)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "expr": "kafka_producer_producer_metrics_request_latency_avg{job=\"$job\", k8s_cluster=\"$k8s_cluster\"}",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Response Rate(ACKS/s)",
   "type": "timeseries",
   "description": "Average number of responses received per second.\nThe response rate represents the rate of responses received from brokers (ACKS) based on ACK setting.\n\nThe rate should be stable!",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_connect_connect_metrics_response_rate{job=\"$job\", k8s_cluster=\"$k8s_cluster\"}",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Batch size average",
   "type": "timeseries",
   "description": "Size of batch if producer is waiting for broker.  16Kb is default",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kafka_producer_producer_metrics_batch_size_avg{job=\"$job\", k8s_cluster=\"$k8s_cluster\"}",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Producer Connections (equal to broker count?)",
   "type": "timeseries",
   "description": "The current number of active connections.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_producer_producer_metrics_connection_count{job=\"$job\", k8s_cluster=\"$k8s_cluster\"}",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Buffer Wait",
   "type": "timeseries",
   "description": "Wait time in buffer before pushing to broker",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(kafka_producer_producer_metrics_bufferpool_wait_time_total{job=\"$job\", k8s_cluster=\"$k8s_cluster\"})",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Compression Average Rate",
   "type": "graph",
   "description": "If it's equal to 1 there is no compression :)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_producer_metrics_compression_rate_avg{job=\"$job\", k8s_cluster=\"$k8s_cluster\"}",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "IO wait time",
     "type": "graph",
     "description": "io-wait-time-ns-avg Average length of time the I/O thread spent waiting for a socket (in ns)\n\nWaiting is caused by producer sending more messages than broker can handle. This should be very low otherwise it's problem.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "kafka_connect_connect_metrics_io_wait_time_ns_avg{job=\"$job\", k8s_cluster=\"$k8s_cluster\"}",
       "legendFormat": "{{client_id}}"
      }
     ]
    },
    {
     "title": "IO Wait Ratio (fraction time IO)",
     "type": "graph",
     "description": "The fraction of time the I/O thread spent waiting.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_io_wait_ratio{job=\"$job\", k8s_cluster=\"$k8s_cluster\"}",
       "legendFormat": "{{client_id}}"
      }
     ]
    },
    {
     "title": "IO Ratio (fraction time IO)",
     "type": "graph",
     "description": "The fraction of time the I/O thread spent doing I/O.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_io_ratio{job=\"$job\", k8s_cluster=\"$k8s_cluster\"}",
       "legendFormat": "{{client_id}}"
      }
     ]
    }
   ]
  }
 ]
}