{
 "title": "Kafka Topics",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "job",
    "query": "ams_kafka_cdc_exporter,sjc_kafka_cdc_exporter,us2_prod_kafka_cdc_exporter,,gce_infra_eu_cdc_collector_kafka_exporter, ams_kafka_exporter, sjc_kafka_exporter, gce_stage_kafka_exporter, gce_us2_alpha_cdc_collector_kafka_exporter, gce_us2_alpha_kafka_cdc_exporter"
   },
   {
    "name": "topic",
    "query": {
     "query": "label_values(kafka_server_BrokerTopicMetrics_OneMinuteRate{job=\"$job\"},topic)"
    }
   },
   {
    "name": "partition",
    "query": {
     "query": "label_values(kafka_cluster_Partition_Value{job=\"$job\",topic=\"$topic\"},partition)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(kafka_cluster_Partition_Value{job=\"$job\",topic=\"$topic\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Topic General Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Primary Partitions",
   "type": "stat",
   "description": "Excluding replicas",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(count(kafka_log_Log_Value{job=\"$job\",topic=\"$topic\",name=\"Size\"}) / max(kafka_cluster_Partition_Value{name=\"ReplicasCount\",topic=\"$topic\",job=\"$job\"}))"
    }
   ]
  },
  {
   "title": "Replication Factor",
   "type": "stat",
   "description": "each partition has replica count - i'm using max() function just in case some partition would reported smaller value but I don't know if it can happen",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kafka_cluster_Partition_Value{name=\"ReplicasCount\",topic=\"$topic\",job=\"$job\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Partition Count",
   "type": "stat",
   "description": "including replicas",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kafka_log_Log_Value{job=\"$job\",topic=\"$topic\",name=\"Size\"})"
    }
   ]
  },
  {
   "title": "Under Replicated partitions count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kafka_cluster_Partition_Value{name=\"UnderReplicated\",topic=\"$topic\",job=\"$job\"})"
    }
   ]
  },
  {
   "title": "In-Sync Replicas",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kafka_cluster_Partition_Value{name=\"InSyncReplicasCount\",topic=\"$topic\",job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Partition Leader in Time",
   "type": "timeseries",
   "description": "Nevermind the value field",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_cluster_Partition_Value{job=\"$job\",topic=\"$topic\",name=\"ReplicasCount\",partition=~\"$partition\"} > 0",
     "legendFormat": "part {{partition}} : {{instance}} "
    }
   ]
  },
  {
   "title": "Partition Replicas in Time",
   "type": "timeseries",
   "description": "Nevermind the value field. I used dirty trick to display this.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_cluster_Partition_Value{job=\"$job\",topic=\"$topic\",name=\"ReplicasCount\",partition=~\"$partition\"} == 0",
     "legendFormat": "part {{partition}} : {{instance}} "
    }
   ]
  },
  { "title": "Topic - Activity / Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Topic Metrics Count All Partitions - $interval irate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(kafka_server_BrokerTopicMetrics_Count{job=\"$job\",topic=\"$topic\",instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{instance}} - {{name}}"
    }
   ]
  },
  {
   "title": "Topic Metrics NumLogSegments",
   "type": "timeseries",
   "description": "Number of log segments (separate files on disk) per partition.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_log_Log_Value{job=\"$job\",topic=\"$topic\",instance=~\"$instance\",partition=~\"$partition\",name=\"NumLogSegments\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Log (Topic) Size - inc. replica partitions / by instance",
   "type": "timeseries",
   "description": "size of single topic as seen by each instance.. because value of all brokers is identical I suppose this is total Topic size",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(kafka_log_Log_Value{name=\"Size\",job=\"$job\",topic=\"$topic\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(kafka_log_Log_Value{name=\"Size\",job=\"$job\",topic=\"$topic\",instance=~\"$instance\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Log (Topic) Size - Sum all brokers - inc. replica partitions / by partition ID",
   "type": "timeseries",
   "description": "size of single topic as seen by each instance.. because value of all brokers is identical I suppose this is total Topic size",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(kafka_log_Log_Value{name=\"Size\",job=\"$job\",topic=\"$topic\",partition=~\"$partition\"}) by (partition)",
     "legendFormat": "{{partition}}"
    }
   ]
  },
  {
   "title": "Log (Topic) Size - Sum All brokers - Primary Partitions Only",
   "type": "timeseries",
   "description": "size of single topic as seen by each instance.. because value of all brokers is identical I suppose this is total Topic size",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(kafka_log_Log_Value{name=\"Size\",job=\"$job\",topic=\"$topic\",partition=~\"$partition\"}) / max(kafka_cluster_Partition_Value{name=\"ReplicasCount\",topic=\"$topic\",job=\"$job\",partition=~\"$partition\"}) by (partition)",
     "legendFormat": "{{partition}}"
    }
   ]
  },
  {
   "title": "Messages in topic - By partition + Total messages",
   "type": "timeseries",
   "description": "size of single topic as seen by each instance.. because value of all brokers is identical I suppose this is total Topic size",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum((max(kafka_log_Log_Value{job=\"$job\",name=\"LogEndOffset\",topic=\"$topic\"}) by (partition)) - (min(kafka_log_Log_Value{job=\"$job\",name=\"LogStartOffset\",topic=\"$topic\"}) by (partition)))",
     "legendFormat": "Total messages"
    },
    {
     "expr": "(max(kafka_log_Log_Value{job=\"$job\",name=\"LogEndOffset\",topic=\"$topic\",partition=~\"$partition\"}) by (partition)) - (min(kafka_log_Log_Value{job=\"$job\",name=\"LogStartOffset\",topic=\"$topic\",partition=~\"$partition\"}) by (partition))",
     "legendFormat": "Partition {{partition}}"
    }
   ]
  },
  {
   "title": "Topic Replication",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "collapsed": true
  },
  {
   "title": "Consumer Lag",
   "type": "timeseries",
   "description": "size of single topic as seen by each instance.. because value of all brokers is identical I suppose this is total Topic size",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kafka_server_FetcherLagMetrics_Value{job=\"$job\",topic=\"$topic\",partition=~\"$partition\",instance=~\"$instance\"}) by (instance,partition)",
     "legendFormat": "{{instance}} - part {{partition}}"
    }
   ]
  },
  {
   "title": "Replication info",
   "type": "timeseries",
   "description": "size of single topic as seen by each instance.. because value of all brokers is identical I suppose this is total Topic size",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(kafka_cluster_Partition_Value{job=\"$job\",topic=\"$topic\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}