{
 "title": "Kafka Clusters",
 "description": "Kafka resource usage and throughput",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "query": "ams_kafka_cdc_exporter,sjc_kafka_cdc_exporter,us2_prod_kafka_cdc_exporter,,gce_infra_eu_cdc_collector_kafka_exporter, ams_kafka_exporter, sjc_kafka_exporter, gce_stage_kafka_exporter, gce_us2_alpha_cdc_collector_kafka_exporter, gce_us2_alpha_kafka_cdc_exporter"
   },
   {
    "name": "request",
    "query": {
     "query": "label_values(kafka_network_RequestMetrics_99thPercentile{name=\"TotalTimeMs\", job=\"$job\"}, request)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Network Processor Avg Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 - (kafka_network_SocketServer_Value{job=\"$job\",name=\"NetworkProcessorAvgIdlePercent\"})*100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Broker Count",
   "type": "gauge",
   "description": "Number of active brokers. We should always have at least 3 brokers.",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(up{job=\"$job\"} == 1))"
    },
    {}
   ]
  },
  {
   "title": "Who is controller now?",
   "type": "graph",
   "description": "There must be always only one controller otherwise we have split brain. ",
   "gridPos": { "h": 5, "w": 8, "x": 13, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "kafka_controller_KafkaController_Value{name=\"ActiveControllerCount\",job=\"$job\"} == 1",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Topic count in cluster",
   "type": "stat",
   "description": "Total topic count as seen by controller.. in case of split brain this value will probably be double of what it should be.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_KafkaController_Value{job=\"$job\", name=\"GlobalTopicCount\"}) > 0"
    }
   ]
  },
  {
   "title": "Partition count in cluster",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum({job=\"$job\",name=\"GlobalPartitionCount\"})"
    }
   ]
  },
  {
   "title": "Offline partitions",
   "type": "stat",
   "description": "This indicator provides only a cluster controller, and it shows the number of cluster partitions that currently have no master replica.",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_ReplicaManager_Value{name=\"OfflineReplicaCount\",job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Under-Replicated Partitions",
   "type": "stat",
   "description": "The Under Replicated Partitions metric displays the number of partitions that do not have enough replicas to meet the desired replication factor. A partition will also be considered under-replicated if the correct number of replicas exist, but one or more of the replicas have fallen significantly behind the partition leader. The two most common causes of under-replicated partitions are that one or more brokers is unresponsive, or the cluster is experiencing performance issues and one or more brokers have fallen behind.",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_ReplicaManager_Value{name=\"UnderReplicatedPartitions\",job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Total partitions reported by brokers",
   "type": "stat",
   "description": "Total partitions reported by each brokers counted together.",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_ReplicaManager_Value{name=\"PartitionCount\",job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Partitions per broker",
   "type": "graph",
   "description": "Keep in mind, that consumer_offsets has 50 partitions.",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_ReplicaManager_Value{name=\"PartitionCount\",job=\"$job\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "How many partitions does the broker lead",
   "type": "graph",
   "description": "Keep in mind, that consumer_offsets has 50 partitions.",
   "gridPos": { "h": 5, "w": 11, "x": 10, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum({job=\"$job\",name=\"LeaderCount\"}) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "UnderReplicatedPartitions",
   "type": "timeseries",
   "description": "Primary partitions who don't match replication factor. It indicates one or more brokers might be down and new replica wasn't setup yet.\n\nhttps://sematext.com/blog/kafka-metrics-to-monitor/\n\nThe Under Replicated Partitions metric displays the number of partitions that do not have enough replicas to meet the desired replication factor. A partition will also be considered under-replicated if the correct number of replicas exist, but one or more of the replicas have fallen significantly behind the partition leader. The two most common causes of under-replicated partitions are that one or more brokers is unresponsive, or the cluster is experiencing performance issues and one or more brokers have fallen behind.",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "kafka_server_ReplicaManager_Value{job=\"$job\",name=\"UnderReplicatedPartitions\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "OfflinePartitionsCount",
   "type": "timeseries",
   "description": "Number of partitions without an active leader, therefore not readable nor writeable.\n\nhttps://sematext.com/blog/kafka-metrics-to-monitor/",
   "gridPos": { "h": 5, "w": 11, "x": 10, "y": 16 },
   "targets": [
    {
     "expr": "kafka_controller_KafkaController_Value{job=\"$job\",name=\"OfflinePartitionsCount\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total failed fetch requests rate 1 min ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_BrokerTopicMetrics_OneMinuteRate{name=\"FailedFetchRequestsPerSec\",job=\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total failed produce requests 1 min rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_BrokerTopicMetrics_OneMinuteRate{name=\"FailedProduceRequestsPerSec\",job=\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "System Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Processor Idle Percent",
     "type": "graph",
     "description": "Average Idleness over all network processors. If it's too high it means there is lot of network activity ",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "yaxes": [
      {
       "format": "percent",
       "label": "Total user+system CPU time spent in sec."
      }
     ],
     "targets": [
      {
       "expr": "avg(kafka_network_Processor_Value{name=\"IdlePercent\",job=\"$job\"}*100) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Request Handler Idle Percent",
     "type": "graph",
     "description": "Average Idleness over all network processors. If it's too high it means there is lot of network activity ",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "yaxes": [
      {
       "format": "percent",
       "label": "Total user+system CPU time spent in sec."
      }
     ],
     "targets": [
      {
       "expr": "kafka_server_KafkaRequestHandlerPool_MeanRate{name=\"RequestHandlerAvgIdlePercent\",job=\"$job\"}*100",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "CPU Usage - irate $interval * 60 == seconds per minute",
     "type": "graph",
     "description": "Total user and system CPU time spent in seconds. Shouldn't reach 60 seconds.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      {
       "format": "s",
       "label": "Total user+system CPU time spent in sec."
      }
     ],
     "targets": [
      {
       "expr": "irate(process_cpu_seconds_total{job=\"$job\"}[$interval]) * 60",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Time spent in GC",
     "type": "graph",
     "description": "Garbage Collector",
     "gridPos": { "h": 8, "w": 11, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "percentunit", "label": "% time in GC" }
     ],
     "targets": [
      {
       "expr": "sum without(gc)(rate(jvm_gc_collection_seconds_sum{job=\"$job\"}[5m]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "graph",
     "description": "Resident memory is what interests yo",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "process_resident_memory_bytes{job=\"$job\"}",
       "legendFormat": "res mem - {{instance}}"
      }
     ]
    },
    {
     "title": "JVM Memory Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 11, "y": 18 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum without(area) (jvm_memory_bytes_used{job=\"$job\"})",
       "legendFormat": "jvm used - {{instance}}"
      }
     ]
    },
    {
     "title": "File descriptors usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 11, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "process_open_fds{job=\"$job\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Topic Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Messages In -  Per Topic - $interval irate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short", "label": "Messages/s" }
     ],
     "targets": [
      {
       "expr": "irate(kafka_server_BrokerTopicMetrics_Count{job=\"$job\",topic!=\"\",name=\"MessagesInPerSec\"}[$interval])",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Log (Topic) size - Per Topic",
     "type": "graph",
     "description": "total topic size over all brokers with all replica partitions",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(kafka_log_Log_Value{job=\"$job\",name=\"Size\"}) by (topic)",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Bytes In - Per Topic  - $interval irate",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "Bps", "label": "Bytes/s" }
     ],
     "targets": [
      {
       "expr": "irate(kafka_server_BrokerTopicMetrics_Count{job=\"$job\",topic!=\"\",name=\"BytesInPerSec\"}[$interval])",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Bytes Out - Per Topic - $interval irate",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "Bps", "label": "Bytes/s" }
     ],
     "targets": [
      {
       "expr": "irate(kafka_server_BrokerTopicMetrics_Count{job=\"$job\",topic!=\"\",name=\"BytesOutPerSec\"}[$interval])",
       "legendFormat": "{{topic}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Traffic Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average request duration (TotalTimeMs)",
     "type": "graph",
     "description": "https://sematext.com/blog/kafka-metrics-to-monitor/",
     "gridPos": { "h": 6, "w": 11, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "avg(kafka_network_RequestMetrics_Mean{name=\"TotalTimeMs\",job=\"$job\"})",
       "legendFormat": "Mean"
      },
      {
       "expr": "avg(kafka_network_RequestMetrics_50thPercentile{name=\"TotalTimeMs\",job=\"$job\"})",
       "legendFormat": "50%"
      },
      {
       "expr": "avg(kafka_network_RequestMetrics_95thPercentile{name=\"TotalTimeMs\",job=\"$job\"})",
       "legendFormat": "95%"
      },
      {
       "expr": "avg(kafka_network_RequestMetrics_99thPercentile{name=\"TotalTimeMs\",job=\"$job\"})",
       "legendFormat": "99%"
      },
      {
       "expr": "avg(kafka_network_RequestMetrics_999thPercentile{name=\"TotalTimeMs\",job=\"$job\"})",
       "legendFormat": "999%"
      }
     ]
    },
    {
     "title": "Average request duration per broker (TotalTimeMs)",
     "type": "graph",
     "description": "https://sematext.com/blog/kafka-metrics-to-monitor/",
     "gridPos": { "h": 6, "w": 11, "x": 11, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "avg by (instance) (kafka_network_RequestMetrics_Mean{name=\"TotalTimeMs\",job=\"$job\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Total Requests Per Sec - $interval rate",
     "type": "graph",
     "description": "https://sematext.com/blog/kafka-metrics-to-monitor/",
     "gridPos": { "h": 7, "w": 11, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (instance) (rate(kafka_network_RequestMetrics_Count{name=\"RequestsPerSec\",job=\"$job\"})[$interval])",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "sum(rate(kafka_network_RequestMetrics_Count{name=\"RequestsPerSec\",job=\"$job\"})[$interval])",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Total Requests Per Sec by Type - $interval rate",
     "type": "graph",
     "description": "https://sematext.com/blog/kafka-metrics-to-monitor/",
     "gridPos": { "h": 7, "w": 11, "x": 11, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (request) (rate(kafka_network_RequestMetrics_Count{name=\"RequestsPerSec\",job=\"$job\"})[$interval])",
       "legendFormat": "{{request}}"
      }
     ]
    },
    {
     "title": "Total Errors Per Sec - $interval rate",
     "type": "graph",
     "description": "https://sematext.com/blog/kafka-metrics-to-monitor/",
     "gridPos": { "h": 7, "w": 11, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (instance) (rate(kafka_network_RequestMetrics_Count{name=\"ErrorsPerSec\",job=\"$job\"})[$interval])",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "sum(rate(kafka_network_RequestMetrics_Count{name=\"ErrorsPerSec\",job=\"$job\"})[$interval])",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Total Errors Per Sec by Type - $interval rate",
     "type": "graph",
     "description": "https://sematext.com/blog/kafka-metrics-to-monitor/",
     "gridPos": { "h": 7, "w": 11, "x": 11, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (request) (rate(kafka_network_RequestMetrics_Count{name=\"ErrorsPerSec\",job=\"$job\"})[$interval])",
       "legendFormat": "{{request}}"
      }
     ]
    },
    {
     "title": "Total FETCH ErrorsPerSec by error - $interval rate",
     "type": "graph",
     "description": "https://sematext.com/blog/kafka-metrics-to-monitor/",
     "gridPos": { "h": 7, "w": 11, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (error) (rate(kafka_network_RequestMetrics_Count{name=\"ErrorsPerSec\",job=\"$job\",request=\"Fetch\"})[$interval])",
       "legendFormat": "{{error}}"
      }
     ]
    },
    {
     "title": "Total PRODUCE ErrorsPerSec by error - $interval rate",
     "type": "graph",
     "description": "https://sematext.com/blog/kafka-metrics-to-monitor/",
     "gridPos": { "h": 7, "w": 11, "x": 11, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (error) (rate(kafka_network_RequestMetrics_Count{name=\"ErrorsPerSec\",job=\"$job\",request=\"Produce\"})[$interval])",
       "legendFormat": "{{error}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Request Durations per Request Type",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 }
  },
  {
   "title": "TotalTimeMs - $request - duration avgs",
   "type": "graph",
   "description": "https://sematext.com/blog/kafka-metrics-to-monitor/",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 41 },
   "repeat": "request",
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(kafka_network_RequestMetrics_Mean{name=\"TotalTimeMs\",request=~\"$request\",job=\"$job\"})",
     "legendFormat": "Mean"
    },
    {
     "expr": "avg(kafka_network_RequestMetrics_50thPercentile{name=\"TotalTimeMs\",request=~\"$request\",job=\"$job\"})",
     "legendFormat": "50%"
    },
    {
     "expr": "avg(kafka_network_RequestMetrics_95thPercentile{name=\"TotalTimeMs\",request=~\"$request\",job=\"$job\"})",
     "legendFormat": "95%"
    },
    {
     "expr": "avg(kafka_network_RequestMetrics_99thPercentile{name=\"TotalTimeMs\",request=~\"$request\",job=\"$job\"})",
     "legendFormat": "99%"
    },
    {
     "expr": "avg(kafka_network_RequestMetrics_999thPercentile{name=\"TotalTimeMs\",request=~\"$request\",job=\"$job\"})",
     "legendFormat": "999%"
    }
   ]
  },
  {
   "title": "Request Durations per Request Type per Broker",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 139 },
   "repeat": "request"
  },
  {
   "title": "TotalTimeMs - 999% worst $request requests",
   "type": "graph",
   "description": "https://sematext.com/blog/kafka-metrics-to-monitor/",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 140 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (kafka_network_RequestMetrics_999thPercentile{name=\"TotalTimeMs\",request=~\"$request\",job=\"$job\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}