{
 "title": "Kafka Consumer",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "k8s_cluster",
    "query": {
     "query": "label_values(kafka_consumer_consumer_metrics_request_rate,k8s_cluster)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(kafka_consumer_consumer_metrics_request_rate{k8s_cluster=\"$k8s_cluster\"}, job)"
    }
   },
   {
    "name": "topic",
    "query": {
     "query": "label_values(kafka_consumer_consumer_fetch_manager_metrics_bytes_consumed_rate{k8s_cluster=\"$k8s_cluster\", job=\"$job\"}, topic)"
    }
   },
   {
    "name": "partition",
    "query": {
     "query": "label_values(kafka_consumer_consumer_fetch_manager_metrics_records_lag{k8s_cluster=\"$k8s_cluster\", job=\"$job\",topic=~\"$topic\"},partition)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Incoming Bytes per second",
   "type": "timeseries",
   "description": "Average number of bytes consumed per second across all topics",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "kafka_consumer_consumer_metrics_incoming_byte_rate{k8s_cluster=\"$k8s_cluster\", job=\"$job\"}",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Fetch rate",
   "type": "timeseries",
   "description": "Number of fetch requests per second from the consumer\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "kafka_consumer_consumer_fetch_manager_metrics_fetch_rate{k8s_cluster=\"$k8s_cluster\", job=\"$job\"}",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  { "title": "Topics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Incoming bytes per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "kafka_consumer_consumer_fetch_manager_metrics_bytes_consumed_rate{k8s_cluster=\"$k8s_cluster\", job=\"$job\",topic=~\"$topic\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Records consumed (messages / sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "kafka_consumer_consumer_fetch_manager_metrics_records_consumed_rate{k8s_cluster=\"$k8s_cluster\", job=\"$job\",topic=~\"$topic\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Records lag (messages)",
   "type": "timeseries",
   "description": "Number of messages consumer is behind producer on this partition",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "kafka_consumer_consumer_fetch_manager_metrics_records_lag{k8s_cluster=\"$k8s_cluster\", job=\"$job\",topic=~\"$topic\",partition=~\"$partition\"}",
     "legendFormat": "{{topic}} part {{partition}}"
    }
   ]
  },
  {
   "title": "Records lag max (messages)",
   "type": "timeseries",
   "description": "Maximum number of messages consumer is behind producer, either for a specific partition or across all partitions on this client",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "kafka_consumer_consumer_fetch_manager_metrics_records_lag_max{k8s_cluster=\"$k8s_cluster\", job=\"$job\",topic=~\"$topic\",partition=~\"$partition\"}",
     "legendFormat": "{{topic}} part {{partition}}"
    }
   ]
  }
 ]
}